publicity.publicity_entity.*:
  type: config_entity
  label: 'Publicity entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    urlpu:
      type: string
      label: 'UrlPu'
    render:
      type: string
      label: 'render' 
    breakpoints:
      type: string
      label: 'breakpoints'   